//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJUSTADOR
    {
        public int id_persona { get; set; }
        public string telefono { get; set; }
        public System.TimeSpan hora_ent { get; set; }
        public System.TimeSpan hora_sal { get; set; }
        public int cve_zona { get; set; }
    
        public virtual ZONALABORAL ZONALABORAL { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
