//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAVEDADLESIONE
    {
        public GRAVEDADLESIONE()
        {
            this.SINIESTROes = new HashSet<SINIESTRO>();
        }
    
        public int cve_grave_les { get; set; }
        public string desc_grave_les { get; set; }
    
        public virtual ICollection<SINIESTRO> SINIESTROes { get; set; }
    }
}
