//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public int id_orden { get; set; }
        public string taller { get; set; }
        public Nullable<System.DateTime> fec_ent { get; set; }
        public int cve_edo_repa { get; set; }
        public int id_siniestro { get; set; }
    
        public virtual EDOREPARACION EDOREPARACION { get; set; }
        public virtual SINIESTRO SINIESTRO { get; set; }
    }
}
