//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZA
    {
        public POLIZA()
        {
            this.SINIESTROes = new HashSet<SINIESTRO>();
        }
    
        public int num_poliza { get; set; }
        public int id_persona { get; set; }
        public string placas { get; set; }
        public string polizaseg { get; set; }
    
        public virtual AUTO AUTO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<SINIESTRO> SINIESTROes { get; set; }
    }
}
