//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINIESTRO
    {
        public SINIESTRO()
        {
            this.ORDENs = new HashSet<ORDEN>();
        }
    
        public int id_siniestro { get; set; }
        public string edo_chofer { get; set; }
        public string condi_clima { get; set; }
        public string condi_terreno { get; set; }
        public decimal importe { get; set; }
        public string video { get; set; }
        public string cp { get; set; }
        public string calle { get; set; }
        public short numero { get; set; }
        public string colonia { get; set; }
        public string delegacion { get; set; }
        public string tipo_accidente { get; set; }
        public short num_lesionado { get; set; }
        public int cve_grave_les { get; set; }
        public int num_poliza { get; set; }
    
        public virtual GRAVEDADLESIONE GRAVEDADLESIONE { get; set; }
        public virtual ICollection<ORDEN> ORDENs { get; set; }
        public virtual POLIZA POLIZA { get; set; }
    }
}
