//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOUSUARIO
    {
        public TIPOUSUARIO()
        {
            this.PERSONAs = new HashSet<PERSONA>();
        }
    
        public int cve_tipo_usu { get; set; }
        public string desc_tipo_usu { get; set; }
    
        public virtual ICollection<PERSONA> PERSONAs { get; set; }
    }
}
