//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONALABORAL
    {
        public ZONALABORAL()
        {
            this.AJUSTADORs = new HashSet<AJUSTADOR>();
        }
    
        public int cve_zona { get; set; }
        public string desc_zona { get; set; }
    
        public virtual ICollection<AJUSTADOR> AJUSTADORs { get; set; }
    }
}
